name: pull request

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: print
      run: echo "HELLO there"
