name: pull request

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    if: (contains(github.event.comment.body, '/runtest'))
    steps:
    - name: print
      run: echo "HELLO there"
